### ISSUE TITLE
Weekly Community Check In 35: Hacktoberfest is here!!!

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/webjack#119]
#### Hi everyone :wave: 

We all at Public Lab :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check:.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

Hackober Fest is here :tada: :tada:
------------------------------------------------ 
To qualify for the official limited edition Hacktoberfest shirt, you must register and then make four pull requests (PRs) between October 1-31 (in any time zone). There are various projects in PublicLab you just need to make 4 pull requests and you will get a free t-shirt and other perks. This year, the first 50,000 participants who successfully complete the challenge will earn a T-shirt. Here is the signup [link](https://hacktoberfest.digitalocean.com)  Lets get hacking folks :man_technologist: :woman_technologist:  

Google Code-In
---------------------
Google Code-in is a contest to introduce pre-university students (ages 13-17) to open source software development. Since 2010, 8,108 students from 107 countries have completed over 40,100 open source tasks!

Because Google Code-in is often the first experience many students have with open source, the contest is designed to make it easy for students to jump right in.

Refer https://codein.withgoogle.com for more details on the program

Call for Mentors: #6238

Google Code-In Tasklist: #6239

Challenge for GSoC and Outreachy Students -> Teach the young generation to code like a pro.
100 tada
Let's see how well our SoC students can manage the immense crowd which we will have from October onwards. Last year I accepted this challenge. Let's see who will accept this challenge this year?

Mentor guidelines https://developers.google.com/open-source/gci/help/oa-tips#mentors

Other than SoC students, we invite everyone to apply for GCI mentorship. Anyone can help us with molding the young generation into the right orientation.
For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### Note to Outreachy participants
-----------------------------------------------
Welcome to PublicLab, happy to have you here :smile: 
Please say hi and introduce yourself so that the community and the mentors can get to know you. Ask for help whenever you need it. If you need help finding first-timer issues or guidelines on how to effectively make contributions or basically anything, people are super nice here :wink: 

Great week ahead everyone :balloon: :balloon:

**Comment by cesswairimu** [comment]
@gauravano
@milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @shubhscoder @sidntrivedi012 @SidharthBansal @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77

**Comment by cesswairimu** [comment]
@ananyaarun @ananya @publiclab-mimi @ananya @hc-barker @starkblaze01 @asquare @pdurbin @HarshKhandeparkar
@newbazz @aSquare14 @vaarigupta @alonpeer @aashna27 @harshithpabbati @jesus-montano @cryptoclidus @mohamed-elalem @konolga @gowtham5699
@jywarren @ebarry @steviepubliclab @StlMaris123

**Comment by pydevsg** [comment]
I am super excited to be part of Google Code In contest and would love to mentor this year 😄

**Comment by jywarren** [comment]
:-) awesome! Thanks all! Welcome to Hacktoberfesters!

Also noting that the Outreachy winter session contribution period opens today! Welcome to Outreachy applicants!

https://github.com/publiclab/plots2/issues/6285

All this means we should work to convert some `fto-candidate` issues into full-fledged `first-timers-only` issues!

https://github.com/publiclab/plots2/labels/fto-candidate

https://github.com/publiclab/plots2/labels/first-timers-only

Thanks, everyone!!!

**Comment by pydevsg** [comment]
I will surely create more __first-timers-issue__ and will review them as much as possible , helping them contribute to the PL community 😄 .

**Comment by ebarry** [comment]
Hello everyone!
I would like your advice on possibly highlighting these Education-related and moderation-related issues for consideration in Hacktober? Do these look ready to go? Are there any questions right off the bat i could answer? Let me know!
Thank you!

Issues related to Education:
https://github.com/publiclab/plots2/issues/6281 - Moderation: move spam off dashboard
https://github.com/publiclab/plots2/issues/6282 - Moderation: change time of mod emails
https://github.com/publiclab/plots2/issues/6244 - Moderation related, but not related to education:
https://github.com/publiclab/plots2/issues/6173 - Ed-related: activity:foo should take wiki page “foo”

**Comment by SidharthBansal** [comment]
Oh great @cesswairimu 
I have labeled some issues with hack October so that Public Lab repository is visible on their website. 
I have also opened up an issue so that people can come at PL too.

**Comment by SidharthBansal** [comment]
Here is the link https://github.com/publiclab/plots2/issues/6412

**Comment by cesswairimu** [comment]
awesome thanks @SidharthBansal

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/plots2/issues/6470. Thanks all
