### ISSUE TITLE
Update gh-pages

### ISSUE THREAD

**Issue by rmeister** [publiclab/webjack#12]
How is an update performed? With a PR from master?

Also, I think the node_modules folder is not necessary and can be removed.

**Comment by jywarren** [comment]
The node modules folder is not used at all in production? 

You can check out the gh-pages branch and pull or merge from the master branch to play the latest changes on top of it.

**Comment by rmeister** [comment]
There are only dev dependencies, though I removed the node_modules.

Done!  Can I close this?

**Comment by jywarren** [comment]
Yep!
