### ISSUE TITLE
Implement a RPC feature (e.g. Firmata) 

### ISSUE THREAD

**Issue by rmeister** [publiclab/webjack#20]
Less interesting due to overhead or dependency constraints:
https://github.com/wheeler-microfluidics/arduino-rpc
https://github.com/cloud-rocket/arduino-json-rpc
https://bitbucket.org/sources/tiny-rpc/wiki/Home

Probably the better choice:
https://github.com/thijse/Arduino-CmdMessenger
https://github.com/firmata/firmata.js

All of this RPC-like implementations currently require either UART or some kind of Wifi/Ethernet shield. For some, there are no JavaScript clients available or only node implementations.

To avoid inserting dependencies/requires in WebJack, I'd say writing a wrapper project for use with Frimata and/or CmdMessenger is the better option.

@jywarren , what's your opinion?

**Comment by jywarren** [comment]
awesome -- i agree and firmata.js looks like the best option.

**Comment by rmeister** [comment]
https://github.com/publiclab/webjack-firmata

I'll close this one if you don't mind.

**Comment by jywarren** [comment]
Great. Hi, Richard - I don't see any recent commits to webjack itself -- is the gh-pages branch showing the latest version?
