### ISSUE TITLE
API method for getting/setting frequencies

### ISSUE THREAD

**Issue by jywarren** [publiclab/webjack#26]
in looking at other applications for this library like browser-to-browser, i was thinking we could make this get/settable. 

https://github.com/quiet/quiet-js can operate at ~19kHz:

> For speaker transmission, there is a profile which transmits around the 19kHz range, which is essentially imperceptible to people (nearly ultrasonic).

**Comment by rmeister** [comment]
Maybe it makes sense to introduce some kind of profiles as constructor parameter? There could be a profile for browser-to-browser communication at higher frequencies, and a profile for use with SoftModem that has echoCancellation enabled to encounter crosstalk.

**Comment by jywarren** [comment]
Sure, well, we could read in an options object and we could provide a set
of common ones for different profiles, yes!

**Comment by rmeister** [comment]
#29

**Comment by jywarren** [comment]
And in #37, making an `connection.options` object that is a getter. This is probably sufficient for now, as we can re-initialize the whole thing to set -- but there is discussion in #37 on creating a `setOptions` method so setting can potentially be done after initialization.

**Comment by jywarren** [comment]
Complete in #42!
