### ISSUE TITLE
add volume "level" indicator to demo

### ISSUE THREAD

**Issue by jywarren** [publiclab/webjack#30]
to help in debugging -- it's good to see that, for example, something blinks when it hears _anything_. Maybe we can just include an existing module for this, and/or blink just one dot called "Volume" or "Sound detected"?

Here's one that's really helpful:

![screen shot 2018-02-07 at 12 31 28 pm](https://user-images.githubusercontent.com/24359/35931542-e73f31a0-0c02-11e8-9ae4-df32302d91e1.png)

**Comment by jywarren** [comment]
Could also link to https://test.webrtc.org/

**Comment by rmeister** [comment]
That's an excellent idea, and maybe I can incorporate parts of it into a first-timer-only issue?

**Comment by jywarren** [comment]
sure! Good idea, though maybe a `help-wanted` issue as a FTO issue should
be something you can spell out in a series of concrete steps. But if you
think it'll be that easy, go for it!

**Comment by jywarren** [comment]
If you could point at a line in the decoder where there's a way to listen or query for activity -- it could just be a place to listen for a 1 or 0, instead of actually listening for volume -- that'd be really helpful -- could this line where `state` is changed to `DATA` work?

https://github.com/publiclab/webjack/blob/master/src/decoder.js#L178

**Comment by rmeister** [comment]
Hm do we really want this stuff inside the code? 

Maybe we can use this example, but only in the code of the demo site:
https://webaudiodemos.appspot.com/volume-meter/index.html

**Comment by jywarren** [comment]
Agreed, this should be in the demo code, and can be pretty much separate from core WebJack.

**Comment by jywarren** [comment]
I like https://webaudiodemos.appspot.com/volume-meter/index.html !!!

**Comment by jywarren** [comment]
Update!  I made a https://p5js.org sketch of an equalizer -- you can also hover your mouse to see the frequency:

https://editor.p5js.org/jywarren/sketches/TsICFM5ZO

It embeds, though maybe we'd need to run it from within the demo for cross- domain security reasons?

```html
<iframe src="https://editor.p5js.org/jywarren/embed/TsICFM5ZO" style="border:0;width:100%;height:400px;"></iframe>
```

Open in a new window here: https://editor.p5js.org/jywarren/full/TsICFM5ZO

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/55114637-da688c00-50b8-11e9-9476-2014eafcc68a.png)

**Comment by jywarren** [comment]
I think i got this working!

![image](https://user-images.githubusercontent.com/24359/55171982-b86e1880-514f-11e9-9619-73e3ef8056a9.png)

**Comment by jywarren** [comment]
I'll leave this open, because we could later expand the frequency range to include browser frequencies of 20,000Hz:

https://github.com/publiclab/webjack#profiles

I can't see how we can set the range the FFT p5JS plugin monitors using options here: 

https://p5js.org/reference/#/p5.FFT
https://p5js.org/reference/#/p5.FFT/analyze

But perhaps we could propose an upstream change to set the range of the FFT -- building on this issue:

https://github.com/processing/p5.js-sound/issues/353

**Comment by jywarren** [comment]
Done!!!
